// Code generated by MockGen. DO NOT EDIT.
// Source: balance_handler.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBalanceManager is a mock of BalanceManager interface
type MockBalanceManager struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceManagerMockRecorder
}

// MockBalanceManagerMockRecorder is the mock recorder for MockBalanceManager
type MockBalanceManagerMockRecorder struct {
	mock *MockBalanceManager
}

// NewMockBalanceManager creates a new mock instance
func NewMockBalanceManager(ctrl *gomock.Controller) *MockBalanceManager {
	mock := &MockBalanceManager{ctrl: ctrl}
	mock.recorder = &MockBalanceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBalanceManager) EXPECT() *MockBalanceManagerMockRecorder {
	return m.recorder
}

// Retrieve mocks base method
func (m *MockBalanceManager) Retrieve(accountNumber string) float32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", accountNumber)
	ret0, _ := ret[0].(float32)
	return ret0
}

// Retrieve indicates an expected call of Retrieve
func (mr *MockBalanceManagerMockRecorder) Retrieve(accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockBalanceManager)(nil).Retrieve), accountNumber)
}
